version: "3.1"

services:
  app:
    build:
      context: ../
      dockerfile: docker/python.Dockerfile
    environment:
      PYTHONBUFFERED: 'true'
    volumes:
      - ../:/backend/
      - ../../frontend/dist/:/frontend/
    ports:
      - 5000:5000
    depends_on:
      - db
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    ports:
      - 5432:5432
    build:
      context: ../
      dockerfile: docker/db.Dockerfile
    # image: mausch/postgres-madlib
    # restart: always
    # environment:
    #   POSTGRES_DB: lalonde
    #   POSTGRES_USER: zaliql
    #   POSTGRES_PASSWORD: password
    #   PGDATA: ./db-init/
    
    # volumes:
    #   - ../db/:/db/
    #   - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
