-- instantiate lalonde demo data
CREATE TABLE lalonde(
  id TEXT,
  treat INTEGER,
  age INTEGER,
  educ INTEGER,
  black INTEGER,
  hispan INTEGER,
  married INTEGER,
  nodegree INTEGER,
  re74 NUMERIC,
  re75 NUMERIC,
  re78 NUMERIC
);
COPY lalonde (
  id,
  treat,
  age,
  educ,
  black,
  hispan,
  married,
  nodegree,
  re74,
  re75,
  re78
) FROM '/db/data/lalonde.csv' CSV HEADER;
CREATE TABLE lalonde_demo (
  pk serial primary key,
  id TEXT,
  treat INTEGER,
  age INTEGER,
  educ INTEGER,
  black INTEGER,
  hispan INTEGER,
  married INTEGER,
  nodegree INTEGER,
  re74 NUMERIC,
  re75 NUMERIC,
  re78 NUMERIC
);
CREATE SEQUENCE lalonde_demo_id_seq;
INSERT INTO lalonde_demo 
SELECT 
  nextval('lalonde_demo_id_seq'),
  id,
  treat,
  age,
  educ,
  black,
  hispan,
  married,
  nodegree,
  re74,
  re75,
  re78
FROM lalonde
ORDER BY id asc;
DROP TABLE lalonde;

-- instantiate flights & weather demo data
CREATE TABLE weather_demo (
  wid SERIAL primary key,
  fog INTEGER,
  hail INTEGER,
  hum INTEGER,
  precipm NUMERIC,
  pressurem NUMERIC,
  lowpressure INTEGER,
  rain INTEGER,
  snow INTEGER,
  heavysnow INTEGER,
  tempm NUMERIC,
  thunder INTEGER,
  vism NUMERIC,
  lowvisibility INTEGER,
  wspdm NUMERIC,
  highwindspeed INTEGER
);
CREATE TABLE flights_demo (
  fid SERIAL primary key,
  carrierid INTEGER,
  carrier TEXT,
  airport TEXT,
  dest TEXT,
  yyear INTEGER,
  quarter INTEGER,
  month INTEGER,
  dayofweek INTEGER,
  hour INTEGER,
  crsdeptime TEXT,
  depdelay NUMERIC,
  depdel15 INTEGER,
  wid SERIAL references weather_demo (wid)
);
CREATE TABLE flights_weather_demo (
  fid SERIAL primary key,
  carrierid INTEGER,
  carrier TEXT,
  airport TEXT,
  dest TEXT,
  yyear INTEGER,
  quarter INTEGER,
  month INTEGER,
  dayofweek INTEGER,
  hour INTEGER,
  crsdeptime TEXT,
  depdelay NUMERIC,
  depdel15 INTEGER,
  wid SERIAL,
  fog INTEGER,
  hail INTEGER,
  hum INTEGER,
  precipm NUMERIC,
  pressurem NUMERIC,
  lowpressure INTEGER,
  rain INTEGER,
  snow INTEGER,
  heavysnow INTEGER,
  tempm NUMERIC,
  thunder INTEGER,
  vism NUMERIC,
  lowvisibility INTEGER,
  wspdm NUMERIC,
  highwindspeed INTEGER
);
COPY weather_demo (
  wid,
  fog,
  hail,
  hum,
  precipm,
  pressurem,
  lowpressure,
  rain,
  snow,
  heavysnow,
  tempm,
  thunder,
  vism,
  lowvisibility,
  wspdm,
  highwindspeed
) FROM '/db/data/weather-airports.csv' CSV HEADER;
COPY flights_demo (
  fid,
  carrierid,
  carrier,
  airport,
  dest,
  yyear,
  quarter,
  month,
  dayofweek,
  hour,
  crsdeptime,
  depdelay,
  depdel15,
  wid
) FROM '/db/data/flights-airports.csv' CSV HEADER;
INSERT INTO flights_weather_demo
SELECT
  fid,
  carrierid,
  carrier,
  airport,
  dest,
  yyear,
  quarter,
  month,
  dayofweek,
  hour,
  crsdeptime,
  depdelay,
  depdel15,
  wid,
  fog,
  hail,
  hum,
  precipm,
  pressurem,
  lowpressure,
  rain,
  snow,
  heavysnow,
  tempm,
  thunder,
  vism,
  lowvisibility,
  wspdm,
  highwindspeed
FROM flights_demo
JOIN weather_demo using(wid);

-- 5M row dataset
CREATE TABLE flights_weather_5000000 (
  fid SERIAL primary key,
  carrierid INTEGER,
  carrier TEXT,
  airport TEXT,
  dest TEXT,
  yyear INTEGER,
  quarter INTEGER,
  month INTEGER,
  dayofweek INTEGER,
  hour INTEGER,
  crsdeptime TEXT,
  depdelay NUMERIC,
  depdel15 INTEGER,
  wid SERIAL,
  fog INTEGER,
  hail INTEGER,
  hum INTEGER,
  precipm NUMERIC,
  pressurem NUMERIC,
  lowpressure INTEGER,
  rain INTEGER,
  snow INTEGER,
  heavysnow INTEGER,
  tempm NUMERIC,
  thunder INTEGER,
  vism NUMERIC,
  lowvisibility INTEGER,
  wspdm NUMERIC,
  highwindspeed INTEGER
);
COPY flights_weather_5000000 (
  fid,
  carrierid,
  carrier,
  airport,
  dest,
  yyear,
  quarter,
  month,
  dayofweek,
  hour,
  crsdeptime,
  depdelay,
  depdel15,
  wid,
  fog,
  hail,
  hum,
  precipm,
  pressurem,
  lowpressure,
  rain,
  snow,
  heavysnow,
  tempm,
  thunder,
  vism,
  lowvisibility,
  wspdm,
  highwindspeed
) FROM '/db/data/flights-weather-5000000.csv' CSV HEADER;
